### ISSUE TITLE
Problems with computeConditionalCS_DeltaSD and createSensitivityResults

### ISSUE THREAD

**Issue by pachard** [asheshrambachan/HonestDiD#2]
Hello, 

I have problems replicating the results when I run the code that appears in your vignette. When I run the command CreateSensitivityResults I get the error "Error in { : task 1 failed - "Incomparable dimensions" and when I run the command ComputeConditionalCS_DeltaSD  I have the error message "mul_dims_promote(lh_dim, rh_dim): incomparable dimensions". The error messages refer to incomparable dimensions not to "non conformable arguments" (that I get if I choose randomly the number of pre and post periods). 

When I googled the error message, I found a link to a R/utilities page describing some code for CVXR Disciplined Convex Optimization. 

I re-installed the package and tried on several computers. All the packages that I was asked to update when installing HonestDiD re up to date. I use Windows 10 but had the same problems on a Mac (Mojave). I run R 3.6.2 version. 

Tell me if you need any other information.

**Comment by asheshrambachan** [comment]
Hi,

I also googled the error you mentioned, "mul_dims_promote" and found this [link](https://rdrr.io/cran/CVXR/src/R/utilities.R#sym-mul_dims_promote), which I think is the R/utilities.R page you mentioned. However, searching through the functions, there is no error message "incomparable dimensions" in the function "mul_dims_promote" -- it looks like the error should say "incompatible dimensions." 

I updated all of my packages as you mentioned and was able to replicate your error (received the error ``incompatible dimensions'' that was traced back to the function "mul_dims_promote" in CVXR). 

I did some investigation and I believe the problem is fixed. It appears like there was an issue with some changes to CVXR that appeared after the updates. I just pushed changes to the package that should (hopefully) address this error. 

Could you try re-installing the package and seeing if this fixes the error for you as well?

**Comment by pachard** [comment]
Hi, 

Sorry for my late reply. Everything works now.
