### ISSUE TITLE
Example using the DRDID package? 

### ISSUE THREAD

**Issue by jyl19** [asheshrambachan/HonestDiD#32]
Hello HonestDiD Team, 

Do you know if there is an example implementation of this approach that uses the DRDiD method? I see the version for CS estimator, but if we have non-staggered data and are using the DRDiD package, is there an existing implementation for that within HonestDID?

And if not, how hard would it be to do this? 

Thanks!

Best,
Josh

**Comment by jonathandroth** [comment]
Hi,

Thanks for the question. I'm a bit confused because the input to HonestDiD
is an event-study. The DRDID package does not produce event-studies: it
considers a setting with one pre-period and one post-period. If you have
many periods, you could of course apply DRDID to different pairs of periods
to manually create an event-study. But I think that's what the event-study
command of the did package does under the hood. Is there some reason not to
just use the event-study produced by the did package?

Best,
J

**Comment by jyl19** [comment]
Hi Jonathan,

Thank you for your reply. It didn't occur to me to run this in the 'did'
package but without staggered treatment timing -- for some reason, I
assumed staggered treatment timing was necessary for the did package to
work. Thank you for clarifying that for me, and thank you for the terrific
work you all have done on crystalizing what the PT assumption actually
means in practice. This package is a real godsend.

Are you planning on developing implementations of other methods for this as
well? I'm very partial to the FECT package (
https://yiqingxu.org/packages/fect/fect.html) as well and was curious if
that approach is reconcilable with your approach to PT here.

Thanks again!

Best,
Josh

**Comment by jonathandroth** [comment]
Hi Josh,

Thanks for the kind note.

Yes, you can use the did package with non-staggered timing (although it's
definitely pitched as a tool for staggered settings, so the confusion is
understandable!).

The theory for HonestDID works for any approach that produces an
event-study with asymptotically normal coefficients. That in principle
should cover fect. The practical question is how easy is it to extract the
beta and sigma from the results of fect to pass as arguments to honestDID.
If you can figure out how to do that, though, then you can just pass those
as the arguments beta and sigma to HonestDID. (If you do, LMK and we can
post an example!)

Jon
